# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This is the core CRUD based service.
  crud:
    networks:
      - shared-network
    image: srvt-crud-amd64
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
  
  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin
    ports:
      - 9411:9411